### ISSUE TITLE
hexo s 时候出现了报错，然后也无法部署和加载网页

### ISSUE THREAD

**Issue by JamieJustTang** [HeliumOI/hexo-theme-ringo#1]
你好，我是一个刚刚接触hexo的小白，打算用您的模板来做自己的个人博客，但是遇到了一些问题。

我git clone了您的代码，然后在本地进行预览，得到了报错：

```
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
**ERROR** {
  err: TypeError: C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\layout.ejs:16
      14|         </div>
      15|       </main>
   >> 16|       <%- partial('_partial/after-footer') %>
      17|   </body>
      18|
      19| </html>

  C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\_partial\after-footer.ejs:10
      8| <% } %>
      9| <!-- mathjax support -->
   >> 10| <% if (theme.mathjax.enable && (theme.mathjax.per_page || page.mathjax)){ %>
      11|     <%- partial('plugin/mathjax') %>
      12| <% } %>
      13| <!-- fancybox support -->

  Cannot read property 'enable' of undefined
      at eval (C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\_partial\after-footer.ejs:30:26)
      at after-footer (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\layout.ejs:27:17)
      at layout (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
      at C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:462:21) {
    path: 'C:\\Users\\hltlt\\Desktop\\IRRT\\Blog\\blog\\themes\\ringo\\layout\\layout.ejs'
  }
} Render HTML failed: index.html

```

随后我进入了localhost:4000，cmd上返回了红色的报错信息：

```
Unhandled rejection TypeError: C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\layout.ejs:16
    14|         </div>
    15|       </main>
 >> 16|       <%- partial('_partial/after-footer') %>
    17|   </body>
    18|
    19| </html>

C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\_partial\after-footer.ejs:10
    8| <% } %>
    9| <!-- mathjax support -->
 >> 10| <% if (theme.mathjax.enable && (theme.mathjax.per_page || page.mathjax)){ %>
    11|     <%- partial('plugin/mathjax') %>
    12| <% } %>
    13| <!-- fancybox support -->

Cannot read property 'enable' of undefined
    at eval (C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\_partial\after-footer.ejs:30:26)
    at after-footer (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (C:\Users\hltlt\Desktop\IRRT\Blog\blog\themes\ringo\layout\layout.ejs:27:17)
    at layout (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\hltlt\Desktop\IRRT\Blog\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:462:21)
```

我也不清楚是因为什么原因，如果您能解答或者解决我的这个问题，那就太好了！

**Comment by Nranphy** [comment]
我这里也出现了同样的问题。。

**Comment by HeliumOI** [comment]
已解决。 <https://github.com/HeliumOI/hexo-theme-ringo/commit/8d3895ecc97b6f9750926bdb8d42a5633ea5b41b>
