### ISSUE TITLE
构建站点时出现了一些错误

### ISSUE THREAD

**Issue by Ghdgtdgu** [HeliumOI/hexo-theme-ringo#2]
执行hexo g命令后, 出现了错误信息:
```ERROR
TypeError: E:\code\ghdgtdgu.github.io\themes\ringo\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

E:\code\ghdgtdgu.github.io\themes\ringo\layout\_partial\article.ejs:22
    20|         </ul>
    21|         <div class="post-content" itemprop="articleBody">
 >> 22|             <%- lazyloadImage(post.content) %>
    23|             <% if (theme.post_copyright.enable === true) { %>
    24|                 <blockquote>
    25|                     <p>文章作者：<a href="<%- url_for() %> "> <%- config.author %>  </a></p>

Cannot read properties of undefined (reading 'lazyload')
    at Object.<anonymous> (E:\code\ghdgtdgu.github.io\themes\ringo\scripts\helpers\lazyload.js:7:16)
    at eval ("E:\\code\\ghdgtdgu.github.io\\themes\\ringo\\layout\\_partial\\article.ejs":26:17)
    at article (E:\code\ghdgtdgu.github.io\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("E:\\code\\ghdgtdgu.github.io\\themes\\ringo\\layout\\post.ejs":10:17)
    at post (E:\code\ghdgtdgu.github.io\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\code\ghdgtdgu.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at E:\code\ghdgtdgu.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\code\ghdgtdgu.github.io\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

执行hexo s预览时也出现同样的报错.
希望能够给予解答.

**Comment by imelonkid** [comment]
> lazyload

按我的方式修改lazyload.js就可以了
<img width="750" alt="image" src="https://user-images.githubusercontent.com/88540395/229975063-e56443db-3977-4397-af9e-55fd138bee53.png">

**Comment by imelonkid** [comment]
主题的全局搜索呢？我看只写了搜索的样式，没有搜索的入口

**Comment by HeliumOI** [comment]
> 主题的全局搜索呢？我看只写了搜索的样式，没有搜索的入口

抱歉，本人在上高中之后就由于学业原因停止了对开发的关注，今年高考结束之后就来写全局搜索功能。
